### ISSUE TITLE
Feature: Ability to run casperjs code linked from a scenario

### ISSUE THREAD

**Issue by sanchothefat** [garris/BackstopJS#102]
I can have a stab at this but Casperjs / Phantomjs are pretty new to me.

My thinking is that where we define a scenario you could reference a casperjs file to run when the readyEvent / delay have happened eg:

```json
{
  "viewports": {
    ...
  },
  "scenarios": [
    {
      "label": "http://example.com",
      "url": "http://example.com",
      "onReadyEvent": "./path/to/casperjs/file.js"
    }
  ]
}
```

Offers full flexibility for those who want to go a bit deeper. I'm looking into the `test.js` to see where / if this could work but any thoughts in the meantime on the idea would be great to hear.

**Comment by garris** [comment]
Hi @sanchothefat.  Thanks for looking into this.  This is a feature that has been requested before.   Here are some comments/ideas...

- maybe change `onReadyEvent` to `onReadyScript` -- just to make it clear that we are linking to a file.

- the ready event handler you are looking for is here...
https://github.com/garris/BackstopJS/blob/master/capture/genBitmaps.js#L97

- in that spot you would probably want to do something like this...
```
    if (scenario.onReadyScript && fs.isFile(scenario.onReadyScript)) {
      var executableJsAsString = fs.read(scenario.onReadyScript);
      // execute that code here
      // or you may be able to import the file in some other way -- just a suggestion
    }
```

- please contemplate this feature and how the two features might interact or support each other...
https://github.com/garris/BackstopJS/issues/94

Let me know if I can help.

Cheers.

**Comment by sanchothefat** [comment]
Awesome, thanks @garris - this is a great place to start. Agreed on your first point, the naming is much clearer, I momentarily forgot it was a json file, no functions :)

#94 looks interesting too. Perhaps a prepackaged script and `scenario.onReadyScript` can be an array. Something along those lines. I'll have a play.

**Comment by garris** [comment]
@sanchothefat this is nice work!  But I am a little concerned that an array of scripts is overcomplicated.  I think the use case is likely to be more simple for most users.   For the minority of users who need multiple file support they can always concat those things in gulp or grunt exactly how they like.   This would reduce complexity on the BackstopJS side -- reading files and handling errors will be an unnecessary pain...

In relation to https://github.com/garris/BackstopJS/issues/94   -- I only mention this because I imagine it makes sense that an `onReadyScript` would run on each of those sub-scenarios -- and that may or may not be a good thing.

In any case, I apologize for possibly distracting you.  I really think you should focus more on your feature... 
- import a casper script and get it to run
- handle any errors gracefully
- provide a test scenario
- document it
- and not worry about #94 because it doesn't even exist yet ;-)

Carry on -- this feature will create a lot of developer happiness!

**Comment by sanchothefat** [comment]
@garris thanks! Re. the array part I see your point - the scripts themselves can do any requiring of other scripts if necessary.

For the test scenario can you point me in the right direction where to add that? Add an example to the `test` folder code or just to the `config.default.json`?

I'll update the readme too.

**Comment by garris** [comment]
yup.  great!  for the test it is very informal.  just create a directory in the `test` folder (maybe call it `onReadyScript`) and drop anything in there that we would need to test this feature -- that would include a backstop.json file and your casper script (and any test html file if you are not using something at a live URL). create any scenarios in there that would test your feature.   Just some basic check.

And yes, also update the config.default.json with a `onReadyScript: null`.  That will let anyone working with the config files that there is this option. The readme should probably describe how to point to a file in the `../../backstop_data/` directory with a content snippet of a simple file.

**Comment by sanchothefat** [comment]
@garris think that's it, let me know if there's anything else you need. Took me a while to figure out jquery doesn't load on the bootstrap page so there's a debug option now to optionally enable the `casper.on('page.error')` stuff.

**Comment by sanchothefat** [comment]
And it's merged! Thanks :)
