### ISSUE TITLE
Testing hover or focus states for multiple elements at the same time

### ISSUE THREAD

**Issue by arronlai** [garris/BackstopJS#1049]
Hi, BackstopJS is really a wonderful regression testing tool, and thanks for providing it.

I wonder if there is a way to test the hover or focus states for multiple elements. In my project there are multiple form elements like &lt;input&gt; &lt;button&gt; on each page, and if I use hoverSelectors or clickSelectors, in my screenshot only the last matched element is hovered or focused, but I don't want to write so many similar scenarios for hovering on different elements. so my question is: is it possible to test hover or focus states for multiple elements on one scenario? 

I'm not sure if I make my point clear, pls tell me if you need more information. Thanks

**Comment by garris** [comment]
hi @aaronjorbin -- thanks for posting.   So, in chrome, the hover behavior is actually created by moving an actual mouse pointer over the element.  Since there is only one pointer there can only be one hover effect at any given time.

I might suggest, instead of using a JSON config, you could create a JS config and maybe add an array of elements selectors you want tested and you could just generate the scenarios right into the the config. 

Cheers.
Garris

**Comment by arronlai** [comment]
Thank you so much, @garris I will try the way you suggested.
