### ISSUE TITLE
Are there plans to support playwright

### ISSUE THREAD

**Issue by wesselbaum** [garris/BackstopJS#1142]
I recently learned about https://github.com/microsoft/playwright which is a project by former puppeteer developers but now working for microsoft instead of goodle and now supporting multiple engines ( Chromium, WebKit and Firefox) wwith a single API. 

Being able to check for Chrome and Firefox would be such a great feature in my opinion.
The API should be similar to puppeteer which is currently implemented.

Any thoughts?

**Comment by garris** [comment]
Yes.  We will absolutely support playwright.  We were just talking about last week.

**Comment by garris** [comment]
If anyone is in a rush -- feel free to add as a new engine and send a PR.

**Comment by fuhlig** [comment]
If it's about Firefox support:
It is supported with pupeeteer 2.1+
https://github.com/puppeteer/puppeteer#q-what-is-the-status-of-cross-browser-support

**Comment by FireGhost** [comment]
I've started an implementation of Playwright: https://github.com/FireGhost/BackstopJS-Playwright

**For now, it does not have all the features that are available for Puppeteer !**

So, the features that works with Playwright right now are:
- viewports
- scenarios (of course)
  - readyEvent
  - readySelector
  - delay
- onReadyScript
- onBeforeScript
- asyncCaptureLimit
- asyncCompareLimit
- misMatchThreshold
- requireSameDimensions
- engineOptions

New features:
- The "browsersTypes" option where you can specify multiple browsers (should work with Puppeteer too). Ex: `"browsersTypes": ["firefox", "chromium", "webkit"]`
- The "hideBrowserConsoleLogs" option, self explained. Set it to "true" in order to hide the console log coming from the browser.

Features that does not work:
- You can only take fullpage screenshot (selectors screenshot is not implemented)
- Reference URL is not implemented
- hideSelector, removeSelector not implemented, but can be done in the onReadyScript
- keyPressSelector, hoverSelector, clickSelector, scrollToSelector not tested/implemented, but can be done in OnReadyScript

**Comment by masi** [comment]
@FireGhost Any updates on this? If you don't want to make a PR, sharing a fork on Github will be appreciated.

**Comment by garris** [comment]
@FireGhost apologies for the delay.  This looks like a great start.  Please do create a PR and let's bring this in.  

We would ultimately want to have parity across engines but it seems ok to start here since this is effectively behind a feature flag.

**Comment by marcdacz** [comment]
Any updates on this. This will enable users to test firefox, chrome and safari. Also, is this supporting docker as well?

**Comment by mayank99** [comment]
@FireGhost @garris Any updates on this? Playwright support would be huge for cross-browser tests

**Comment by garris** [comment]
Hey guys -- so sorry-- no updates from my side.  I would be happy to create a branch and have someone "own" this integration project to get it done!

**Comment by mayank99** [comment]
@garris I would potentially be down to finish what FireGhost started several months ago. It would just be slow as I have limited time

**Comment by garris** [comment]
@FireGhost is it ok for us to pull your changes into a new branch?

**Comment by FrostyShosty** [comment]
I've just completed and submitted a (linked) PR to add Playwright support (not based on the work by @FireGhost).  All comments and feedback are very welcome!  I believe all scenario features are tested and working.  The only two features that I didn't test were running in Docker and the ignoreCSP script.  I'd be happy to test these given a suitable test case.
