### ISSUE TITLE
Failing to create bitmaps_test folder in GitHub Actions after upgrade to 6.2.0

### ISSUE THREAD

**Issue by davidcmoulton** [garris/BackstopJS#1466]
We have successfully been using `backstopjs` in our GitHub Actions with 6.1.4, using `npx backstop --docker test`. On upgrading to 6.2.0 the backstop run in GitHub Actions fails, erroring with a bunch of:
```
Browser Console Log 0: JSHandle:BackstopTools have been installed.
Error: EACCES: permission denied, mkdir 'backstop_data/bitmaps_test'
```
We suspect the regression may be stemming from the changes in user introduced in https://github.com/garris/BackstopJS/commit/6d221a275686bad7c7b58fd7ff1325e7067e1bcb.

**Comment by garris** [comment]
@tkrah 👆 any thoughts on this one?

**Comment by tkrah** [comment]
Sorry, with that few input, can't really comment on that, I don't use GitHub actions, so can't comment on those either.
I use that image of 6.2.0 without a problem, eaccess looks like a permission problem though, op should investigate in that direction.

**Comment by garris** [comment]
Thank you @tkrah for the fast enhancement!   

@davidcmoulton can you please validate that this patch solved your issue?

**Comment by erkannt** [comment]
I'm part of the same ensemble as @davidcmoulton and can confirm that the patch works for us:

https://github.com/sciety/sciety/pull/2168

**Comment by theghostbel** [comment]
Does it work when running from Windows?

**Comment by tkrah** [comment]
> Does it work when running from Windows?

depends - if you have an environment where id is available yes, if not than you need to customize the dockerCommandTemplate like written in the README.md of backstopjs to use one which does work for your environment.

**Comment by tkrah** [comment]
You need to use a username which your docker daemon in windows does know about. As I don't know your setup, you have to find out yourself which username you need to provide. You can also try "--user root" but that will get you files owned by root - which may or may not be a problem for you to be removed later because of the ownership, ymmv.

**Comment by theghostbel** [comment]
ok, `--user root` works well, no problems so far. Should add this to docs, quite a tricky problem to investigate. 

```
dockerCommandTemplate: 'docker run --rm -it --user root --mount type=bind,source="{cwd}",target=/src backstopjs/backstopjs:{version} {backstopCommand} {args}'
```

**Comment by tkrah** [comment]
@garris Your code, your decision ;-). 

Running as root is considered bad practice, their are numerous articles (use your search engine of your choice) about why it should not be done and I don't see why backstopjs needs that root privilege.

For me the current default is the better one, because before the change I did not care about my user settings, it did run it as root by default and I ended up having root owned files in my user directory which I was unable to delete now (that's why I changed the user to the node user in the first place which the node base image does create).
After that I needed to configure an explicit user and change the default template to be able to have a usable image (to me).

So having a default solution which sets the user with `$(id -u)` which makes all those files owned by the user who runs that (me) is an improvement (at least to me), because I don't have files now which I can't delete anymore.

`root` of cause will always run, because that is the user which normally is always there - but it has it nitpicks though like described.

Maybe you can change the default template to make a distinction here.

Is Linux as running OS is detected (https://www.npmjs.com/package/detect-os or something of your likes - I am not an npm expert) we use the default template like it is now (with `--user $(id-u):$(id -g)`) and if something else is detected you use `--user root` ?
Just an idea - you can of cause use `root` again like in the past although I would not vote for that, but in the end, your the one in charge here and it is your decision, I just did add my 2 cents here, I hope it helps you in finding a decision. ;-)

**Comment by tkrah** [comment]
@garris It is hard to cope with windows here, docker daemon runs in a virtual machine there - that's why the local user is not known as seen above.
So if you don't want to cope with 2, we have to use root again as a default because of that, as that is the only user in that VM and of cause we must revert that too, if you want to honor your point 3 that users should not read docs (although I find that point questionable - why do you have docs in the first place if no one should read them ;-) - it is like man pages, I am always happy if `man <tool>` does have a usable output, but I guess that is just personal preference - nothing I have to impose on anyone).

To be honest, I can live with going back to root as default to honor your principle 2+3 and we just change the docs to mention the "new" old default template and document that at least all non windows users should **really** consider to use the current template as a default to fix the attributes on the files in their config, although that would mean that the default smoke tests will again produce files with wrong attributes, but I am not going to run that one so ofter anyway :-P.

If you agree on that I can provide a PR, but it may take a few days, short of time at the moment.

**Comment by garris** [comment]
@tkrah I was thinking about slightly better ways to address this.  We could log out a warning if we find `--user root` in the docker command template -- and we could link it to [here](https://github.com/garris/BackstopJS#changing-the-default-docker-command) in the docs.   So for beginners, running it for the first time just works, but users will see a warning in the logs until they fix the security weakness.

**Comment by tkrah** [comment]
I would have removed the user command from the docker file all together, so I don't know if we would have that template still in use.
Let's just document it (windows user have no chance anyway to change it, which would again will be against your rule 2).
I'll prepare a PR and we can discuss it there further. ;-)

**Comment by tkrah** [comment]
Fixed and can be closed @garris .

**Comment by garris** [comment]
Ah!  Yes.  Thank you.  Cheers
