### ISSUE TITLE
refactor for backstop-core implementation

### ISSUE THREAD

**Issue by garris** [garris/BackstopJS#164]
`gulp.run()` was used in the initial implementation of BackstopJS and is now deprecated.   It's time we go back and straighten out these logic issues in a more ~~Gulp-friendly~~ (platform-agnostic) way.  Any assistance on this refactor is greatly appreciated!

**Comment by YuliaTsareva** [comment]
In my opinion it would be great if BackstopJS wasn't built on top of Gulp at all :)
It is an extra dependency for projects that does not use Gulp. And can stop developers from adopting BackstopJS.

**Comment by garris** [comment]
@YuliaTsareva -- I think you have a good point.   What framework or library (if any) would you use if you were to refactor?

**Comment by garris** [comment]
Maybe this... https://github.com/remy/clite

**Comment by YuliaTsareva** [comment]
@garris Sorry, I am not familiar with such frameworks... if I were to refactor, I definitely would investigate this question :)
I haven't tried clite, may be it is a good tool. But I would suggest to check if there is any well-known project (and with more stars).

**Comment by klausbayrhammer** [comment]
@YuliaTsareva @garris I thought about this a couple of weeks ago as well. What I would love to do is to extract something like a `backstop-core` module. This `backstop-core` would basically consist of all components which are needed in order to run backstop and expose the needed functions as plain javascript-functions. Then we could do something like `gulp-backstop` (or just call it `backstop` to make it backwards compatible) which is a gulp-wrapper for the functions (and dependencies) exposed by backstop-core. If we would need a CLI-runner we could create something like `backstop-cli` or `backstop-clite`

I think this could also greatly benefit CI integration #135 and tools like grunt-backstop because they can just use the `backstop-core` part. And furthermore we would also avoid exposing internal tasks (like `the jscs-task` to our api (which are all tasks in the gulpfile).

**Comment by garris** [comment]
@klausbayrhammer     Yes, Totally. I really like the bring-your-own-wrapper direction.

**Comment by wjramos** [comment]
+1 on @klausbayrhammer's suggestion of a more agnostic core package

**Comment by garris** [comment]
Ok.  FWIW:  I have just simplified installation by removing all global NPM dependencies and migrated the `Gulp <command>` idiom to the more compatible `npm run <command>`  idiom.  So, all that is now needed for installation is `npm install backstopjs` _no more `npm install <package> -g` required._

Everything is backward compatible. `Gulp <command>` will actually still work -- so long as the additional global gulp installation is performed.

This update was really inspired by @YuliaTsareva -- I have always found the installation process to be too clunky -- and I think this change makes BackstopJS feel more agnostic and familiar to non-gulp users.  So, thanks for the comments!

To be sure, I still wholly support any `backstop-core` effort.  Just wanted to see if I could move that notion forward with the time I had.   Carry on people.

**Comment by klausbayrhammer** [comment]
@garris this is a great first step! As a second step we could try to have those `npm run` scripts call plain javascript functions (which can be used by the gulp-tasks as well). This would be a pretty neat improvement if you want to use backstop in an existing gulp-build, because you can get rid of gulp-chug. Although there are a couple of things to consider, I think this refactoring has a digestible size

**Comment by JulienPradet** [comment]
Hi!

I was wondering if I could be of any help here and which task I could do. Is there anyone actively working on the `core` thing ?

I'm working on a project ([Pigment-Store](https://github.com/JulienPradet/pigment-store)) that's supposed to come as a all-in-one Documentation + Automated Visual Testing for React Apps. (I don't want to do my advertising here, it's just to explain why I'm willing to help :)) And BackstopJS seems to suit my needs for the Automated Testing part. However, if a `core` existed it would be much easier for me to interact with the library.

Moreover, once you've got a clear `core`, it's quite easy to come up with a CLI. [minimist](https://www.npmjs.com/package/minimist) is great for parsing arguments. You just need to map them to your functions later on.

I won't be of much help for another 10 days. But if by any change, help is still needed by then, I'll be glad to help.

**Comment by garris** [comment]
@JulienPradet Yup, that would be great.  I would love to see the refactoring happen and I am very happy to see BackstopJS get bundled into your testing app.   @levithomason had looked at this but I don't think he is actively working on it.  I will just ping him to make sure.  Otherwise you're welcome to have-at-it!   Please let me know how I can help.

**Comment by levithomason** [comment]
I'll be on vacation this week through next Monday. We've just finished incorporating backstop into our stack to prove it out. Now that this is done, the cli is on my list. My first step here was going to be  pulling all the gulp tasks into plain functions, then bootstrapping a cli with the same commands. 

Feel free to get started on of this and I'll follow up behind.

**Comment by garris** [comment]
@JulienPradet @levithomason Thanks guys. 👍

**Comment by garris** [comment]
Closed by #259
