### ISSUE TITLE
should the Bless command move the test images into the reference image folder?

### ISSUE THREAD

**Issue by mrdevin** [garris/BackstopJS#196]
This would save me from having to take reference screenshots again.

**Comment by garris** [comment]
Sorry for the delay replying -- I see where you're going with this.   The `Bless` you're referring to should maybe be called BlessConfig -- because that is really it's purpose.   

As far as images go -- there is already feature request to enable "promoting" a test image (or all images) to a reference image.   If you have created that, please feel free to submit a PR -- it would be super useful. 

Cheers.

**Comment by garris** [comment]
Accidentally closed.
