### ISSUE TITLE
phantomjs error upon using gulp-version of BackstopJS

### ISSUE THREAD

**Issue by mathesond2** [garris/BackstopJS#235]
Hi, first off: I absolutely love BackstopJS and have found it to be a really, really simple and necessary tool for visual regression testing, especially having never done it before. I recently created an  [example repo] (https://github.com/mathesond2/visual-regression-testing) to show other colleagues how BackstopJS works, and now looking into it a month later, I am getting this error when I run the  `gulp reference` task:

`CasperJS: Fatal: [Errno 2] No such file or directory; did you install phantomjs?`

I have been able to fix this by globally installing PhantomJS on my machine (fix [found here] (https://github.com/narainsagar/node-casperjs-aws-lambda/issues/1)), but understand that Phantomjs-prebuilt is a node module which comes with BackstopJS, so I shouldn't have to install globally? The only change from last month and now that I can see is that backstop has gone up a version number (1.3.4 to 1.3.5) and wanted to give a heads up.

Thoughts?

**Comment by garris** [comment]
@mathesond2 Thank you so much for posting.    I took a look at your example repo and it looks like your documentation is a little bit out of date.   The BackstopJS install now installs everything you need with `npm install backstopjs`.  Global Gulp, CasperJS and PhantomJS installs have been unnecessary since version 1.2.0.   

Also, the supported commands have all been moved to npm:  `npm run test`, `npm run reference`, `npm run genConfig`.   The Gulp commands still work for backward compatibility -- but Gulp is being phased out.  The only quirk left is having to `cd node_modules/backstopjs` to run commands -- this will also be phased out with Gulp.  _Note: We will add a gulp shim so that prior integrations will still continue to work._

In any case, it would be great if you could validate all of this in your environment -- maybe just try to install in a different location.  Please let me know if you run into any issues and it would be great if you could update your documentation to reflect the recent contributions when you get a chance.   

Cheers!

**Comment by mathesond2** [comment]
Awesome!! Thanks so much, I've been scratching my head for a while this morning so that is great. Also, I'll be updating ASAP. 👍

**Comment by svwu** [comment]
I guess you brought problems with this update...
When I install BackstopJS, I get the following error:
/backstop/node_modules/backstopjs/node_modules/gulp/node_modules/gulp-util/node_modules/array-differ/index.js:2
module.exports = (arr, ...values) => {
^
SyntaxError: Unexpected token .
at Module._compile (module.js:439:25)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)

**Comment by garris** [comment]
@svwu thanks for posting.  I haven't seen that issue and the current version has been out for weeks.  What version NPM and node are you using?

**Comment by svwu** [comment]
Oh yeah...
The new version of BackstopJS also required an update for my NodeJS and NPM version.
Sorry for this issues, my bad...

**Comment by garris** [comment]
:+1:
