### ISSUE TITLE
Choose default browser to open report

### ISSUE THREAD

**Issue by rhacker** [garris/BackstopJS#269]
In my computer, backstopjs keeps choosing to open a browser in virtual machine. Is there any way I can define which browser i want to use instead ? 

Thanks

**Comment by garris** [comment]
This is a guess but -- if it's OS X you can try changing your default browser to a native version of chrome.

**Comment by rhacker** [comment]
I'm not sure about this, Mac Chrome is being set as default browser in my mac and it works fine with another app except backstopjs.

**Comment by dirkloose** [comment]
Yes, it's the same here. OS X with Parallels tries to open report in IE on Win10? Default browser on Mac is Safari. Of course I can open it manually in any Browser after test is done, but it opens Parallels and tries to reach localhost on Default Windows Browser (which is pretty annoying).

Default browser from my terminal opens correctly in safari (as any other click to any link does):
> open http://localhost:3333/compare

Must be something else... I thought I might edit it like browser in "browersync" and use "google chrome" instead of "browser", but it didn't work (https://browsersync.io/docs/options#option-browser). Maybe this is some kind of default behavior by some used components? 

Needs to be tracked down, I guess... any ideas?

**Comment by garris** [comment]
Maybe you could try BackstopJS version 2?  It's in beta mode here... https://github.com/garris/BackstopJS/blob/version_2_0/README.md

It opens the browser using a completely different method.  Would be interesting to see if it fixes your issue.

**Comment by dirkloose** [comment]
I gave the 2.0 Beta a try today. It opens the file in the local default browser via direct file reference (file:///Volumes/server/.../backstop_data/html_report/index.html). That works fine for me, since the reporting does not try to open the browser on parallels/windows anymore.

Very good job on the new version with a lot of great improvements. I like the global installation, since we use it on several projects. And making the browser-reports better accessible makes it easier to share them. Thanks a lot.

**Comment by garris** [comment]
Great to hear!   Cheers.
