### ISSUE TITLE
Different reference names in different environments

### ISSUE THREAD

**Issue by godban** [garris/BackstopJS#291]
Have a trouble with running tests in CI (previous week or so all was fine):

    Bitmap file generation completed.
    COMMAND | Executing core for `report`
    COMMAND | Command `report` ended with an error
    COMMAND | Reference image not found: /home/travis/build/godban/godban.github.io/tests/visual/backstop_data/bitmaps_reference/01876053680_Index_0_logo_0_phone.png

Happening because of prefix in reference name **01876053680**_Index_0_logo_0_phone.png which is different from my local & committed one 2005537259_Index_0_logo_0_phone.png

It is looks like prefix is environment depending. Why it was changed? Previously all was fine without prefixes.

**Comment by garris** [comment]
@godban Thanks for posting.  The hash was added because we anticipate users with many config files may run into name conflicts across scenarios with matching names from different configs.  Therefore BackstopJS attempts to create a unique ID for each un-named config.   This does present an issue when sharing files.

To avoid this conflict you can simply name your scenarios by using the ID property. Please see the docs here... https://github.com/garris/BackstopJS/tree/version_2_0#required-config-properties

Please let me know if this solves your issue -- I don't want this new feature to overly complicate the app.

Thanks!

**Comment by godban** [comment]
@garris thx for quick response

Setting **id** resolves this issue.

**Comment by garris** [comment]
Glad it worked out.  Cheers!
