### ISSUE TITLE
Looks like we're almost ready to release the NPM install version.

### ISSUE THREAD

**Issue by garris** [garris/BackstopJS#31]
@jehoshua02 @lewisnyman  I think we will want to merge the new work on master into the npm_install branch and validate.   With all the clean up you guys put in I think we could call this 1.0.   Sound like a good next step?

**Comment by jehoshua02** [comment]
Before calling it 1.0 I might refactor from a set of gulp tasks into a command line tool.

**Comment by jehoshua02** [comment]
But I'm all for releasing a new version for the npm install.

**Comment by garris** [comment]
@jehoshua02 What are you picturing for a command line tool?

**Comment by jehoshua02** [comment]
Start simple with something like this ...

```shell
cd ~/projects/myCoolProject
npm install --save-dev backstop #[1]
./node_modules/.bin/backstop init #[2]
./node_modules/.bin/backstop reference #[3]
./node_modules/.bin/backstop test #[4]
git add backstop_files backstop.json; git commit #[5]
```

1. Install backstop and dependencies via npm. I'd like this to install casperjs and phantomjs as well. We'd have to do some kind of magic to make these versions visible within backstop code.
2. Run command to generate `backstop.json` config file in the current directory (`~/projects/myCoolProject`).
3. Run command to capture reference screenshots based on `backstop.json` found in current directory.
4. Run command to capture test screenshots based on `backstop.json` found in current directory.
5. Track backstop generated files. This would contain reference and test screenshots and report formats for human or automated machine consumption (html, json). Backstop can create a `.gitignore` in this directory for test screenshots and reports so only reference screenshots are tracked. I'd like to run backstop in a continuous integration environment and cause the build to fail if the differences cross some threshold.

Alternatively, backstop could be installed globally, but it would only act as a wrapper and run the local version if installed, in effect, the same commands as above, much like bower or gulp ...

```shell
npm install -g backstop #[1]
cd ~/projects/myCoolProject
backstop init #[2]
backstop reference #[2]
backstop test #[2]
git add backstop_files backstop.json; git commit #[3]
```

1. Install with npm globally.
2. Commands do exactly the same thing as before. The command is just nicer.
3. All the same files are generated in the current directory.

Even when installing globally, I'd still recommend installing locally as well. The only reason for the global install is to make the command nicer.

**Comment by jehoshua02** [comment]
So I'd release the npm only install. Then I'd release the command line interface as 1.0.

**Comment by lewisnyman** [comment]
Sounds really nice, this would bring it inline with the conventions of a lot of npm-managed tools.

**Comment by garris** [comment]
Yup.  All sounds good to me.  

Let's release this as 0.4.0 then.   I can create another branch to merge master and npm_install.   We can test that -- then move that back to master & release.

I think 0.4.0 will open BackstopJS up to more developers who have some async client side stuff they need to test, and the improved config and gulp implementations will make it easier to extend and encourage more contribution.

The CLI is a nice touch because it gives the app a little more conventional feel -- and that will appeal to some developers as well.

Something to consider...  I've gotten some feedback from several engineers who wanted to use a central  BackstopJS instance to work across multiple projects.  I think this is a very valid use case and again, would likely widen the user base in a significant way.   Obviously, there are a lot of ways to implement this -- one, simple way would be to allow for custom screenshot file locations relative to the top level project directory (above /node_modules/).  If that were the case it would open the door for saving screenshots to say, backstopFiles/projectName/<backstop screenshot folders>   It would then be straightforward matter to build configuration swapping.  This also fixes the huge transgression of saving user data in node_modules.

Just an idea there.

I am writing a guest blog tutorial where I'll announce this release -- my guess is that will go live in approx 3 weeks.  I'd like to give you guys credit on the backstopjs homepage for your contributions -- that sound ok?  Let me know if you want me to link your names to any particular URL.

Alright.  Awesome.

GS

**Comment by jehoshua02** [comment]
@garris 

__backstop_files__

> ... a central BackstopJS instance to work across multiple projects.
> ... custom screenshot file locations relative to the top level project directory ...
> ... fixes the huge transgression of saving user data in node_modules.

I like to keep everything specific to a project with that project so they can be updated and committed together so I have a hard time grasping why anyone would want a central backstop instance. I'm open to it, but I think some healthy scrutiny won't hurt anything.

Backstop could be installed globally, I could create a centralized backstop project somewhere on the system, and configure `backstop.json` however I needed to to run against multiple projects.

So for the 1.0 I'd just put the `backstop_files` (following the format of `<tool>_<what>` as in `bower_components` or `node_modules`) in the current directory, where the command is run. Then, perhaps in a minor release, add a configuration option to put them in a custom location. This could be anywhere on the system.

Also, I was thinking that 1.0 would install casperjs and phantomjs, and even slimerjs, as dependencies via npm and do some "magic" to ensure that those versions are used by default when running backstop commands (probably by adding `./node_modules/.bin` to the path or something). Then see if that doesn't meet all use cases. If there is a truly compelling use case that can't be accommodated in a pleasing way with what is already available, then expose a configuration option, probably a boolean, to opt out of the "magic" and use global casperjs, phantomjs, and slimerjs executables. Something like `"use_local_bin"` with a default `true`.

&lt;aside class="philosophy"&gt;
In all things I'm a fan of keeping the "public interface" (the parts we intend for use, and intended usage of those parts) lean, simple, and sensical so that it's easier for users to learn and use, and easier for us to maintain. So I resist expanding the public interface without first observing and feeling a real need to, and try to shrink and simplify the public interface whenever possible. I keep everything else private, or at least quiet, only documenting the public interface.
&lt;/aside&gt;

> ... credit on the backstopjs homepage for your contributions 
> ... any particular URL.

How about a [widget](https://github.com/blossom/contributors) for that?

**Comment by jehoshua02** [comment]
My lean public interface philosophy is influenced by ["Getting Real"](https://gettingreal.37signals.com/toc.php).

**Comment by garris** [comment]
I had an hour so I pulled the trigger today.   The contributions widget used an outdated api so that did not make it into this version.   Thanks for your help guys!   Follow up on other topics later.   Cheers.  GS
