### ISSUE TITLE
Refactor into a Command Line Tool

### ISSUE THREAD

**Issue by jehoshua02** [garris/BackstopJS#32]
See discussion:

https://github.com/garris/BackstopJS/issues/31#issuecomment-72604270
https://github.com/garris/BackstopJS/issues/31#issuecomment-72792279

1. [ ] Define public interface (commands, file locations, configurations).
2. [ ] Outline refactoring steps to get there.

**Comment by jehoshua02** [comment]
@garris Tell me what you think about this ...

__Commands__

+ ./node_modules/.bin/backstop init
+ ./node_modules/.bin/backstop reference
+ ./node_modules/.bin/backstop test

(I'd like to tackle the global install in the next release, which would sweeten up this command syntax.)

__Files__

```tree
+ ./ (current directory where command is run)
| + backstop_files/ (contains all backstop generated files, other than config)
| | + reference/ (generated by reference command)
| | + test/ (generated by test command)
| | + report/ (generated by test command)
| | | + html/ (probably just the compare app)
| | | + report.json (format for programmatic consumption)
| | + .gitignore (ignores test and report but not reference)
| + backstop.json
```

__Configurations__

+ Freeze until after command line refactor is done.

**Comment by garris** [comment]
Hey @jehoshua02 thanks so much for all the effort you're putting into it.  Ill be out of the loop for a few days -- I am completely slammed with obligations for the rest of the week maybe longer.   

Quickly tho: there are missing commands. 'gulp echo', 'gulp bless', 'gulp genConfig' and stuff to manually run the server.  Also, there is no need for a report directory.  The only file that changes is report.json.

I have some questions too.  Will follow up as soon as my queue get manageable.  Best.  GS

**Comment by jehoshua02** [comment]
@garris No worries. I'm juggling quite a bit myself. Respond when, and only when, you can.

I've updated my spec to include echo, bless, start, stop. Though I was thinking that the html report could be a static app that could be opened in file protocol without the server. Each project would have their own copy of the html report (I'm coming from PHPUnit). We can talk more about it. We can preserve current functionality while we think about it.

We'll pick up when you have time.

**Comment by ArmorDarks** [comment]
+1 for such refactoring.

I really hope that Gulp or Grunt versions would be implemented by independent tasks instead of being build on top of Gulp.

**Comment by WillsB3** [comment]
Would this refactor allow me to use Backstop without having to write to a config file? I'm generating my config object in Node (dynamically, as it parses URLs from a sitemap.xml and then creates a scenario for each) and, as far as I can tell, currently I have to write the resulting config object to disk before calling `npm test -- --configPath=...`.

If this issue is describing what I think it is, it'd allow developers to `require()` the Backstop module and use it's API from within their own Node scripts right? If this is the case I assume it also means we won't need to build on top of Gulp anymore?

Or did I completely misunderstand this suggestion :D

**Comment by garris** [comment]
@willsb3   Hey, good news -- you already have the option to `require()` a BackstopJS config.    See the readme file...  https://github.com/garris/BackstopJS/blob/master/README.md#using-a-js-based-config-file-version-100

It would be great if you could post your site map.xml > BackstopJS-config solution -- I'm sure there are others who would benefit from that example!

Also, FYI, that refactoring effort is in progress here... https://github.com/garris/BackstopJS/issues/164

**Comment by WillsB3** [comment]
@garris I had seen that documentation, but that still doesn't do what I need. As explained, I need to call Backstop from within my own Node script, because we are generating the JSON on the fly as a result of scraping our sitemap. Hence currently we are generating the JSON, and then trying to run backstop by doing something like this:

```js
// Have to run the bless task because I generate the "reference" screenshots by using the live sites sitemap.xml, while the "test" screenshots are generated using a sitemap on a local development build of the site.
execSync('gulp bless --configPath=../../backstop/config.js', {
  cwd: 'node_modules/backstopjs',
});

var bs = spawn('npm', ['run', 'test', '--', '--configPath=../../backstop/config.js'], {
  cwd: 'node_modules/backstopjs',
});

bs.stdout.on('data', function(data) {
  console.log(data.toString());
});

bs.stderr.on('data', function(data) {
  console.log(data.toString());
});

bs.on('close', function(code) {
  console.log('Exiting with code: ' + code);
});

bs.on('error', function(error) {
  console.log('Error: ', error);
});
```

This is pretty nasty (and doesn't even fully work yet (as I'm battling another error Backstop is throwing during the npm test), but surely there should be no reason I have to write any sort of config to disk. Ideally, I could do something like this:

```js
var backstop = require('backstop');
var config = generateMyConfigDynamically();

backstop.go(config);
```

Here I'm just requiring Backstop and using an API like other normal node libraries. The current behaviour means I have to write a config to disk, and then do nasty things with exec/execSync to call npm scripts from within my own script.

I don't really see why this tool is all built on top of Gulp, it seems to just make things more complicated, and means that users can't do much customisation if they have a slightly different workflow to what the tools author expects? Seems to me that this tool could be a standalone node package, with a separate gulp wrapper package that users can use if they want to integrate it into their own gulp workflow. The whole "cd into node_modules/backstop and then run it's gulp things" just adds confusion and extra dependencies in my eyes, and limits how it can be integrated into larger systems.

Having said all that, Backstop looks like an great tool, and I'd love to hear your thoughts on if you think there's room for improvement in this area, and if so how I might be able to help?

P.S Let me know if you think this would be better discussed in a separate issue.

Many thanks for the time and effort you've put into this tool so far 👍

**Comment by garris** [comment]
I think your best bet is to break out your config generation from the rest of your app and use that standalone as your BackstopJS config.   Then you can kick off BackstopJS as you like from your existing build flow.  

I think your comment about Gulp making things _"complicated"_ is a bit too easy for you to make in hindsight.  The reason the tool is built on Gulp is because it allowed us to work very quickly and validate the usefulness of our direction in the beginning -- and by beginning I mean the first 2 years.   So I consider the decision to use Gulp as critical to having created something useful that thousands of users can benefit from.   And Yes, you have to `cd node_modules/backstop` -- but after that it's **total utility for free.**

In any case, as I already mentioned there is an effort to refactor BackstopJS into a more mature package -- threads here #232 and here #162.   @JulienPradet and @levithomason are leading this so please coordinate with them if you would like to contribute to that process.   Any help in this area would be greatly appreciated.
