### ISSUE TITLE
Testing hover states

### ISSUE THREAD

**Issue by malcomio** [garris/BackstopJS#40]
It's common for menus etc to be displayed on hover/focus of certain elements.

Is it possible to include this in tests?

If so, please provide documentation on this.

Maybe I need to read the Casper/Phantom docs...

**Comment by garris** [comment]
Your hunch is right. You can learn how to do these kinds of tests in the Casper docs.

**Comment by malcomio** [comment]
This article might be useful: https://helloanselm.com/2014/testing-css-states-with-phantomcss/

Ideally there'd be some documentation on setting up these tests within the backstop.json file.

**Comment by lewisnyman** [comment]
I wonder if this moves beyond the config-only simplicity of BackstopJS. If you want to test interactions, you need to write scripts, I think a much better tool would be PhantomCSS.

**Comment by garris** [comment]
@malcomio @lewisnyman Totally completely agree with Lewis on this.  I even mention PhantomCSS as a great tool for that kind of thing in this article... http://davidwalsh.name/visual-regression-testing-angular-applications

That said, I think the interactivity makes sense in some *limited* contexts -- like where you might want to wait-for-and-then-dismiss (e.g. click 'cancel') an email signup popup that overlays *every single page* (or app state) for all first time visitors.   This is not so much because I want to test the interaction -- but the interaction is a dependency of the tests I want to do.  Hope that makes sense...

For that reason it *might* be very helpful to be able to somehow include-or-require arbitrary casper code -- but I'd really want to draw the line at duplicating PhantomCSS functionality or use cases.
