### ISSUE TITLE
'backstop approve' doesn't update reference files if there were no source files.

### ISSUE THREAD

**Issue by sashamorozov** [garris/BackstopJS#427]
Thank you for the great option, really like it!

But I have a little problem.
When I added new scenario to the config and run `backstop test`, it shows me that there is nothing to compare. It's right. After the test I run `backstop approve`, but the test screenshots are not added to the references! Although they should.

Please help! 
Thanks.

**Comment by garris** [comment]
Yup.  Totally agree.   I really want to fix it.   The fix is to detect a missing reference and substitute the file here... `backstopjs/capture/resources/selectorNotFound_noun_164558_cc.png` as the reference and the compare instead of running the regular compare.  If we do that the approve will work.   If you look at what approve actually does you will see why that works.   

We just happen to be in the middle of a big compare.js refactor at the moment so it is hard to make changes there until that code stabilizes.

I'd also like to see the approve get built out a little bit.  Show you which files it will copy.  enable it to accept a filter arg etc.  That stuff would be great.

**Comment by NaorHai** [comment]
{
  "id": "prod_test",
  "viewports": [
    {
      "name": "phone",
      "width": 320,
      "height": 480
    },
    {
      "name": "tablet_v",
      "width": 568,
      "height": 1024
    },
    {
      "name": "desktop",
      "width": 1024,
      "height": 768
    }
  ],
"scenarios": [
  {
    "label": "My Local Test",
    "url": "../../index.html",
    "hideSelectors": [],
    "removeSelectors": [
    ],
    "selectors": [
      "nav",
      ".jumbotron",
      "body .col-md-4:nth-of-type(1)",
      "body .col-md-4:nth-of-type(2)",
      "body .col-md-4:nth-of-type(3)",
      "footer"
    ],
    "readyEvent": null,
    "delay": 0,
    "onReadyScript": null,
    "onBeforeScript": null
  }
],
  "paths": {
    "bitmaps_reference": "backstop_data/bitmaps_reference",
    "bitmaps_test": "backstop_data/bitmaps_test",
    "casper_scripts": "backstop_data/casper_scripts",
    "html_report": "backstop_data/html_report",
    "ci_report": "backstop_data/ci_report"
  },
  "casperFlags": [],
  "engine": "phantomjs",
  "report": ["browser"],
  "debug": false
}

**Comment by garris** [comment]
Fixed in v2.6.14 https://github.com/garris/BackstopJS/commit/f52d89db155d4f4d8f833926518077e7e7e265cc
