### ISSUE TITLE
Rendering image different between Chrome engine and PhantomJs

### ISSUE THREAD

**Issue by patriciamarchand** [garris/BackstopJS#487]
Hello,
I updated Backstop to version 3.0.7 and all my test fail with a big mismatch Percentage. I think it's  because the image rendering is different between the two version. I compare the two image in Photoshop. Do I have to regenerate all my reference? This can introduce some unwanted regression...

![snag-0027](https://user-images.githubusercontent.com/6225238/28892905-856d4880-779d-11e7-8378-5153cc124ec2.png)
![snag-0023](https://user-images.githubusercontent.com/6225238/28892926-9a99a15e-779d-11e7-982e-6b0e0510e6cb.png)

**Comment by garris** [comment]
@patriciamarchand    Thank you for testing the new version!   Yes -- chrome renders differently than phantom so you can expect that you will need to update your references.

Just a note:  I remember that you had issues before with text rendering across platforms.   Were you able to address that?

**Comment by patriciamarchand** [comment]
@garris Ok then, I will be carefull when I will update the reference. I'm also migrate to Bootstrap 4 so I dont have the choice to pass to Chrome engine who support flexBox grid. 

The other issue, still on it. Takes longer due to holidays...

Thanks

**Comment by garris** [comment]
Just a suggestion-- use  `backstop approve`  Instead of `backstop reference`.

When running `backstop approve` command, all images (with changes) from your most recent test run will be *promoted to your reference collection*.   This way you know exactly what changes will be kept.

SEE: "filtering tests and references by scenario" for a note on approving changes after running backstop test using the --filter argument.
