### ISSUE TITLE
Font Awesome icons

### ISSUE THREAD

**Issue by anton-kulagin** [garris/BackstopJS#521]
Good day, i`m using a lot of icons from font awesome and when make screenshots they shows this icons wrong.  Maybe there is some way to solve this issue? 
P.S. I can make more screenshots if it`s need.

![image](https://user-images.githubusercontent.com/3931244/29766207-a44684d0-8be6-11e7-88b7-9e110f35605e.png)

**Comment by josephmcasey** [comment]
Hi @anton-kulagin ! Could you provide the reproduction steps necessary for me to replicate this issue, and I could help you resolve this?

**Comment by anton-kulagin** [comment]
Steps to reproduce : 
1. Create html markup and put on page one of the icons of font awesome (here a link to icons http://fontawesome.io/icons/  )  . 
2. Create reference and run backstop test. 
3. You will see that this icon is broken.

**Comment by PhilippeVay** [comment]
Are you using default PhantomJS engine or `chromy` or `slimerjs`?  
I tested http://fontawesome.io/icons/ directly with backstopJS (installed 1 month ago), either `chromy` engine or `phantom` and icons are successfully displayed in a screenshot of `#new` element. It's grayish because there's an overlay (capturing `body` will show that. My Firefox profile shows no modal and overlay probably because I'm using an adblocker) but otherwise icons are fine on Windows 10 x64 / either Chromium 61 (Chromy) or Phantom / backstopJS 3.0.1

**Comment by anton-kulagin** [comment]
@garris , @josephmcasey , @PhilippeVay  Thanks for helping, i don`t know what i do wrong first time, but now it works.
