### ISSUE TITLE
First time usage, BackstopJs did not create the initial reference images...

### ISSUE THREAD

**Issue by pstephenwille** [garris/BackstopJS#829]
...which lead to test failures with a message about failing to find any reference images.  To get around this I created `bitmaps_reference` dir and copied the images into it.    My setup steps were:

`backstop init` followed by `backstop test`.

Is this normal, or should I expect the first time usage to create the reference images?

**Comment by garris** [comment]
@pstephenwille You are experiencing expected behavior.   Here is the workflow...  https://github.com/garris/BackstopJS#the-backstopjs-workflow

1) Per the workflow... If you initialize a new backstop instance you will not have any reference files. The following command starts you off fresh...
```
backstop init
```

2) Running a test without any reference files will test your current configuration scenarios against _nothing_.   The expected behavior is that a report will show all the files you just generated but all the scenarios will "fail" because you haven't yet told backstop what files should be considered _correct_.  The idea here is you can see all the _reference candidates_ before approving them 
```
backstop test
```

3) If you are satisfied with the test images in the report after running `backstop test` you can go ahead and _approve_ them.  Doing this will create the backstop_reference directory with the correct files in there...
```
backstop approve
```

Subsequent tests will compare against your now approved screenshots. And so on...

Does that make sense?  Is there maybe a better way to communicate this?  Please let me know.

It would be great if someone could make a 2 minute video to get this point across and help to onboard new users.

**Comment by pstephenwille** [comment]
Perfect!  Works like a charm.  I wasn't expecting test failures, but now that I understand the purpose of a reference image, the docs make sense.  

A video is great idea.  If I can finagle it, I will.
