### ISSUE TITLE
Specify path for the backstop.json config file

### ISSUE THREAD

**Issue by Archiolidius** [garris/BackstopJS#87]
Is it possible to specify path for the backstop.json config file?

**Comment by klausbayrhammer** [comment]
+1

**Comment by garris** [comment]
The short answer is no.  You can specify locations of the screenshots (as of v6.0) but that's about it.  If this were to be enabled how would you expect it to be implemented?

**Comment by klausbayrhammer** [comment]
Probably as parameter you pass to the gulp tasks? Or even better as a property in the `package.json`?

**Comment by garris** [comment]
Oh right, that _would_ be pretty useful.  I owe the project a new roadmap.  I will add this feature to it.

**Comment by klausbayrhammer** [comment]
If you let me know which way you prefer I'd be happy to contribute a PR

**Comment by garris** [comment]
That would be fabulous.   

I like command line approach because it provides a very universal API -- without any specialized knowledge about how gulp works.

I think you would only need to modify paths.js to make this work...

https://github.com/garris/BackstopJS/blob/master/gulp/util/paths.js

You would want to check for a supplied path parameter, if one exists check for a valid file, and if that exists, set `paths.activeCaptureConfigPath` With the supplied path.

Should not be too difficult.

**Comment by garris** [comment]
Ok.  just tested this.  Works beautifully!   It's merged to master.   Release forthcoming!
