### ISSUE TITLE
Add CJK (Chinese, Japanese, Korean) language support to the docker image

### ISSUE THREAD

**Issue by ptmkenny** [garris/BackstopJS#932]
Feature request: It would be great if the chrome browser supplied with the Docker image supported the Japanese and other Asian languages.

I'm trying to test a Japanese language site with this and none of the text is rendered:

![test2](https://user-images.githubusercontent.com/1451472/49084086-d73bcb80-f291-11e8-8790-29ffead1eacb.PNG)

I don't know what needs to be done to get Japanese support working, but I do know I use the Selenium headless chrome image and that displays Japanese properly:
https://hub.docker.com/r/selenium/standalone-chrome-debug/

**Comment by lpeabody** [comment]
I also just ran into this. Big +1 from me. Our biggest projects are all multilingual right now and we can't test these characters.

**Comment by lpeabody** [comment]
The StandaloneChrome Docker image at one point has this in it's inheritance:

https://github.com/SeleniumHQ/docker-selenium/blob/cab7e4b0a2357ae36902ff47bcd827ed96f95c32/NodeBase/Dockerfile#L59-L71

I have to wonder if that is what installs the library.

**Comment by lpeabody** [comment]
I bashed into the running container and installed all libraries listed above except for fonts-tlwg-loma-otf and ttf-ubuntu-font-family because they were not available in an existing apt list.

I can confirm that this allowed the Japanese language to render as expected.

@ptmkenny if you extend the Dockerfile to include that RUN command (minus the above mentioned font packages) you should be good to go.

**Comment by garris** [comment]
@lpeabody -- great work!   Thanks for the insight.   If someone can PR the docker file change I would be happy to pull that in!

**Comment by lpeabody** [comment]
@garris PR opened.
