### ISSUE TITLE
Run script after screenshot

### ISSUE THREAD

**Issue by tonyxu-io** [garris/BackstopJS#943]
The onReady script will click some buttons to get screenshots and then I need to undo button clicks (Recover state, so next time test is run it can do the same action again).
Is there a way to run any script after screenshot taken?

**Comment by chrisalexander55** [comment]
Is anyone home???

**Comment by garris** [comment]
There is no onAfter.  Backstop scenarios are stateless.  Each scenario calls your web app in a new browser.  It's up to you what cookies and interactions you use to create a state.

**Comment by garris** [comment]
@nsp27  I believe your question is different from @tonyxu-io.   If you have a flow with 3 clicks and you want to take a screenshot after each click then this means you want to test 3 states.  A scenario basically maps to a state so that means you'll need 3 scenarios. 

In this case I would simply copy your scenario three times.   The clickSelectors helper takes an arbitrary array of selectors so your three scenarios would maybe be identical except for the clickSelectors property which might be...
`["selectorOne"]` On the first scenario 
`["selectorOne", "selectorTwo"]` on the second
`["selectorOne", "selectorTwo", "selectorThree"]` on the third

Hope that helps!

**Comment by garris** [comment]
@chrisalexander55   Sorry for the delays, it's been a busy month.

**Comment by tonyxu-io** [comment]
Garris reminded another way to solve my problem. Instead of running script to do clean up job after screenshots, I can however move the clean up job before running next screenshots.
For other use cases, feel free to open separate issue, closing this one now.
